### ISSUE TITLE
[Mechanics] will bolt heads damage anything?

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-twelve#15]
Can bolt heads that are here damage the field or opponent when the robot spins?

![image](https://user-images.githubusercontent.com/5435954/202251200-8f2da0b3-f730-4d6c-88e2-affe70e78253.png)

**Comment by kennolot** [comment]
Made the cut 1mm bigger so it hides the bolt heads in this circular cutout, this shouldn't now damage anything
