### ISSUE TITLE
[Mechanics] room at rollers

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-twelve#16]
Is it intentional that there is room between the roller shaft and top cover?

![image](https://user-images.githubusercontent.com/5435954/202251520-982c9da7-8cfa-4d41-a619-d37bb3a751a2.png)

**Comment by kennolot** [comment]
Yes, this shouldn't be a problem right?

**Comment by Akustav** [comment]
Most likely not. Wanted  to know as to why it was done like this.
