### ISSUE TITLE
[Mechanics] no hole in wheel means less adjustment

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-twelve#18]
Currently the closest the wheel can be to the motor is this:

![image](https://user-images.githubusercontent.com/5435954/202856725-67c26e89-d903-4c16-96f3-2300845f469e.png)

To increase it you can shorten the fastener (A) and cut a hole into the wheel body for the shaft to move into (B):

![image](https://user-images.githubusercontent.com/5435954/202857106-6910dd4d-8fd3-473a-86da-69acb8823d1c.png)

**Comment by kennolot** [comment]
Fixed if I understood the problem exactly

**Comment by Akustav** [comment]
You understood yes, but the current assembly has interference: 
![Uploading image.png…]()
