### ISSUE TITLE
PC power cable socket missing

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-twelve#24]
I can not find it on the chassis

**Comment by kennolot** [comment]
![Capture](https://user-images.githubusercontent.com/104031547/206672586-025de4e6-8648-4fdd-97ce-b8294eca5a22.PNG)

I used these circular holes as the multi purpose solution to route all the cables through, what am I missing?

**Comment by Akustav** [comment]
https://ut-robotics.github.io/picr22-home/basketball_robot_guide/mechanics/design.html#_pc_power_adapter_socket This is missing
