### ISSUE TITLE
What blocks balls from getting into the chassis?

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-twelve#27]

**Comment by kennolot** [comment]
Will be using the same flexible "plastic-like" material that was used on the test robot or whatever similar is available on-site.

**Comment by Akustav** [comment]
Then I need to see how this is attached. A model representation is also welcome

**Comment by Akustav** [comment]
If you plan to use such a method make it visible in the model as well. Personally I would not suggest this solution since drilling so many holes in a round component can be tricky.

What I suggest is to add a band of black plastic that is retained by the top and bottom plates, something like this:
![image](https://user-images.githubusercontent.com/5435954/206861634-04428df3-85ad-4b41-821a-cbf66e220f8f.png)

Fastening is done onto another spacer piece with 2 screws. Something like this:
![image](https://user-images.githubusercontent.com/5435954/206861675-90c63c9a-8335-4ae1-8230-390156424a80.png)
