### ISSUE TITLE
No electronics inside chassis

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-twelve#28]
There is no mainboard or step-up converter in the model.

**Comment by kennolot** [comment]
Model wise just downloaded random one from the internet. As for the actual part then probably the same one as the test robot, the thing is that I haven't heard anything from our electronics so I'm not sure even if work is being done.

**Comment by Akustav** [comment]
When the electronics guy does nothing, expect to mount the existing electronics. Currently it is done well with the motor boards but the mainboard and step-up converters are completely wrong. If you can not find a model online, take measurements yourself.
