### ISSUE TITLE
Camera FOV pyramid incorrect angles

### ISSUE THREAD

**Issue by maidlam** [ut-robotics/picr22-team-twelve#31]
The angles of the camera FOV pyramid are too big, showing an incorrect FOV.

The angles for the RGB sensor of the camera should be:
Vertical 42°
Horizontal 69°

https://www.intelrealsense.com/depth-camera-d435i/

**Comment by Akustav** [comment]
Is still wrong, currently it is 81.3 x 48.5 degrees
